version: 2

models:
  - name: stag_customerorders
    description: One record per customer
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stag_customers
    columns:
      - name: customer_id
        description: This model cleans up customer data
        tests:
          - unique
          - not_null

  - name: stag_orders
    description: This model cleans up order data
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stag_customers')
              field: customer_id
  - name: stag_suppliers
    description: This model clean supplier data
    config:
      # Basic Configs
      materialized: incremental
      # unique_key: id
      incremental_strategy: merge
      # Advanced Configurations
      on_schema_change: "sync_all_columns" 
    columns:
      - name: supplier_id
        description: This model cleans up customer data
        tests:
          - unique
          - not_null